export const people = [
    {
        name: "Hamilton Rademaker",
        phone: "(211) 485-6341",
        email: "cum@protonmail.couk",
        country: "Sweden",
        numberrange: 0,
    },
    {
        name: "Guy Plamondon",
        phone: "(844) 327-5107",
        email: "ultrices.posuere@icloud.org",
        country: "Chile",
        numberrange: 8,
    },
    {
        name: "Hasad Rietveld",
        phone: "(513) 440-1561",
        email: "consequat.purus.maecenas@aol.net",
        country: "Turkey",
        numberrange: 8,
    },
    {
        name: "Boris Royer",
        phone: "(446) 573-2485",
        email: "velit",
    },
    {
        name: "Melissa Bouwmeester",
        phone: "1-191-963-8278",
        email: "donec.nibh.quisque@hotmail.net",
        country: "United Kingdom",
        numberrange: 2,
    },
    {
        name: "Troy Victor",
        phone: "1-258-454-0522",
        email: "integer.aliquam@protonmail.ca",
        country: "Germany",
        numberrange: 2,
    },
    {
        name: "Aristotle Aakster",
        phone: "1-487-325-6844",
        email: "justo@protonmail.edu",
        country: "South Africa",
        numberrange: 6,
    },
    {
        name: "Athena Kappel",
        phone: "(831) 602-6284",
        email: "vitae@protonmail.org",
        country: "Colombia",
        numberrange: 7,
    },
    {
        name: "Reed Mertens",
        phone: "1-271-943-5874",
        email: "nulla.dignissim@aol.couk",
        country: "France",
        numberrange: 5,
    },
    {
        name: "Zephania Victor",
        phone: "1-814-434-6620",
        email: "non.dapibus@aol.org",
        country: "Ireland",
        numberrange: 9,
    },
    {
        name: "Gray Fontaine",
        phone: "1-686-815-0259",
        email: "non.leo.vivamus@icloud.net",
    },
];
